### ISSUE TITLE
Feature : Import Helpers

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#134]
I've been working on a library of helper functions that make importing JSON onto your `CoreData` objects using `AlecrimCoreData` and `SwiftyJSON` incredibly easy using generics.

It's something that I think would be a benefit to the community. I'm looking into open-sourcing it, but I'm not sure what the best place to put it is. Since its use depends on the use of `AlecrimCoreData`, it might make sense as a subspec of this library. Would you be interested in including it here, or should I create a separate repository?

**Comment by vmartinelli** [comment]
Hello.

I would like to apologize for the delay in response. I had a health problem and recently I needed surgery because of it. Now I'm fine, but I'm still in after surgery period.

About the library, I'm very excited to see it working. :-)

I think a separated repository will be a better place, since it uses two third-party libraries (ACD and SwiftJSON).

Please feel free to contact me if you need further help. I can not promise I'll answer as readily, but I'll try.

**Comment by AnthonyMDev** [comment]
Alright thanks. That's kind of what I was thinking. I'm looking into cleaning up my library a bit and making a few things more configurable.
