### ISSUE TITLE
Can't initialize Context

### ISSUE THREAD

**Issue by netoleal** [Alecrim/AlecrimCoreData#18]
If I try to create an instance of AlecrimCoreData.Context, the instance is always nil.

Do you have any idea on what I'm doing wrong? Is there any setup that I have to do before to try to create this instance?

This is my current structure:

```
final class XPDataContext: NSObject {
	var user: AlecrimCoreData.Table<XPUser> { return AlecrimCoreData.Table<XPUser>(context: self.context!) }
	var context:AlecrimCoreData.Context! = AlecrimCoreData.Context()
}

// --

class XPContextManager: NSObject {
	class var shared: XPContextManager {
		struct Static {
			static var instance:XPContextManager?
			static var token: dispatch_once_t = 0
		}
		
		dispatch_once(&Static.token){
			Static.instance = XPContextManager( )
		}
		
		return Static.instance!
	}
	
	var dataContext:XPDataContext!
	
	override init( )
	{
		dataContext = XPDataContext( )
		super.init()
	}
}

XPContextManager.shared //this is ok
XPContextManager.shared.dataContext //this is ok too
XPContextManager.shared.dataContext.context //This is nil
```

the context property is always nil

Thanks!

**Comment by bettimms** [comment]
Same here, it's always showing 
fatal error: unexpectedly found nil while unwrapping an Optional value

for the dataContext?!

let dataContext = DataContext()!

final class DataContext: AlecrimCoreData.Context {
    
    var events:      AlecrimCoreData.Table<Event>     { return AlecrimCoreData.Table<Event>(context: self) }
    
}

**Comment by RunOnSoftware** [comment]
The documentation says the models must exist before you run the app.  What I have found is that if you make changes to the models after you have run your app, the context will return as nil too.  Have you tried getting rid of the sqlite tables as I mentioned above?

**Comment by bettimms** [comment]
These files you mentioned on previous post as far as i know are created on simulator Documents folder, so yes i delete them all, they will be deleted also when you delete the app from simulator(what i already tried) but still the same issue.It's strange because when i try almost anything and any change inside the AlecrimCoreDataExample project it works ( i tried and deleted whole object model and created new one and there it works, but it doesn't work on new project)?!
Thank you

**Comment by bettimms** [comment]
Just solved it and i wanted to share. The problem is that managedObjectModelWithName on the Stack class is not validated to accept name with spaces in case of getting the name from bundle.
So the error was coming as result of trying to create the ManagedObjectModel with name that contains white spaces.
So i solved this issue as follows:

// I added this method to validate the default name from bundle
private class func validateManagedObjectModelName(name:String)->String?
    {
        var myArray : [String] = name.componentsSeparatedByString(" ")
        
        var validatedName = name.stringByReplacingOccurrencesOfString(" ", withString: "_", options: nil, range: nil)
        
        return validatedName
    }


// MARK: - private class methods
    
    private class func managedObjectModelWithName(var name: String?, bundle: NSBundle) -> NSManagedObjectModel?
    {
//Here is the validation of name
        if let managedObjectModelName = validateManagedObjectModelName(name!)
        {
            if let managedObjectModelURL = bundle.URLForResource(managedObjectModelName, withExtension: "momd")
            {
                if let managedObjectModel = NSManagedObjectModel(contentsOfURL: managedObjectModelURL)
                {
                    return managedObjectModel
                }
            }
        }
        
        return nil
    }


Regards

**Comment by bettimms** [comment]
Just solved it and i wanted to share. The problem is that managedObjectModelWithName on the Stack class is not validated to accept name with spaces in case of getting the name from bundle.
So the error was coming as result of trying to create the ManagedObjectModel with name that contains white spaces.
So i solved this issue as follows:

```javascript
// I added this method to validate the default name from bundle
private class func validateManagedObjectModelName(name:String)->String?
    {
        
        var validatedName = name.stringByReplacingOccurrencesOfString(" ", withString: "_", options: nil, range: nil)
        
        return validatedName
    }


// MARK: - private class methods
    
    private class func managedObjectModelWithName(var name: String?, bundle: NSBundle) -> NSManagedObjectModel?
    {
//Here is the validation of name
        if let managedObjectModelName = validateManagedObjectModelName(name!)
        {
            if let managedObjectModelURL = bundle.URLForResource(managedObjectModelName, withExtension: "momd")
            {
                if let managedObjectModel = NSManagedObjectModel(contentsOfURL: managedObjectModelURL)
                {
                    return managedObjectModel
                }
            }
        }
        
        return nil
    }

**Comment by FredJiang** [comment]
let dataContext = DataContext(managedObjectModelName:"whatDid")!

this solved my problem
