### ISSUE TITLE
Add distinct method to return unique values

### ISSUE THREAD

**Issue by bettimms** [Alecrim/AlecrimCoreData#33]
Hi there,
Is there in plan to add distinct method to return unique values?!

**Comment by vmartinelli** [comment]
Hello.

To have distinct results, we have to set the result type of the fetch request to NSDictionaryResultType and inform the properties to fetch, so we have dictionaries as results instead of managed objects. An AttributeQuery class was in test for this. I hope to resume testing this feature soon.

Thank you.

**Comment by vmartinelli** [comment]
An early version of this class (AttributeQuery) was added to project in "develop" branch. Maybe it would meet the need?

**Comment by bettimms** [comment]
I did an extension to the 'Table' but as you mentioned the issue is that's returning Dictionary type while I'm interested  to not lose the generic behavior of Entity ('T').
I still didn't update to Swift 1.2 because of some dependencies on some libraries that are not updated yet, so I'm still stuck with old version.
By the way thank you, and congrats for your great work. It was a need to have something like EF on iOS core data too, and as far as i saw this is the closest to it.

**Comment by vmartinelli** [comment]
We can continue working on it. If you have any idea how to implement keeping the type of entity, please tell me. Thank you. :-)
