### ISSUE TITLE
how to init managedObjectModelName

### ISSUE THREAD

**Issue by FredJiang** [Alecrim/AlecrimCoreData#53]
kCFBundleNameKey is not what I want, I changed the Bundle name in plist file

if self.managedObjectModelName == nil {
    if let infoDictionary = self.mainBundle.infoDictionary {
        self.managedObjectModelName = infoDictionary[kCFBundleNameKey] as? String
    }
}

fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by vmartinelli** [comment]
Hello.

You can subclass the (generated) data context and set the `managedObjectModelName` as follow:

```swift
class CustomizedContext: Context {

    convenience init?() {
        let contextOptions = ContextOptions(stackType: .SQLite)
        
        // set the managed object model name
        contextOptions.managedObjectModelName = "MyModelName"
        
        // call the designated initializer
        self.init(contextOptions: contextOptions)
    }
    
}
```

Other options for AlecrimCoreData can be changed this way too.

**Comment by tonglil** [comment]
But how do you do this then?
```swift
let dataContext = DataContext()!
```
It says missing argument for `rootManagedObjectContext`.

**Comment by tonglil** [comment]
I'm trying to change the context options because since [version 1](https://github.com/tonglil/AlecrimCoreDataFork) you have changed the location of the sqlite file, but I nee the app to load the previous file.

**Comment by vmartinelli** [comment]
After subclassing the original context class, perhaps using the `persistentStoreRelativePath` together with the `managedObjectModelName` property of the `contextOptions` parameter it can work. So you can initialize the subclassed context class as you exemplified.

**Comment by tonglil** [comment]
Right, I understand I can change the path to the file, thank you.

However, I was unable to get this ["Sample"](https://github.com/Alecrim/AlecrimCoreData/blob/master/Samples/AppExtensionDataContext.swift) to work because it won't let me create the context.

```swift
import AlecrimCoreData

let dataContext = CustomizedContext(what to put in here?)! // missing argument for rootManagedObjectContext, unable to leave it blank.

class CustomizedContext: Context {
    convenience init?() {
        let contextOptions = ContextOptions(stackType: .SQLite)

        // set the managed object model name
        contextOptions.managedObjectModelName = "MyModelName"

        // call the designated initializer
        self.init(contextOptions: contextOptions)
    }
}
```

**Comment by bhowell2** [comment]
@tonglil - Based on what you just created, you don't put anything there, because the convenience initializer already initializes the class with the correct `ContextOptions` (assuming that is all you want to set). However, you don't really need to do your own initialization there.. You could simply forgo the initializer and do `CustomizedContext(contextOptions: contextOptions)`

Make sure that your Model is in the same bundle, see this from `ContextOptions`:
```
    // MARK: - public properties - bundles
    public let mainBundle: NSBundle = NSBundle.mainBundle()
    public var modelBundle: NSBundle = NSBundle.mainBundle()            // you will have to change this if your xcdatamodeld file is not in the main bundle (in a framework bundle, for example)
```

**Comment by tonglil** [comment]
@bhowell2 
- If I leave it empty, swift won't let me compile, throwing a `missing argument for parameter 'rootManagedObjectContext' in call` error.

- I want to change some of the contextOptions, specifically `contextOptions.managedObjectModelName` and `contextOptions.persistentStoreRelativePath`. That is why I am calling `self.init` with custom context options.

- Unable to initialize the custom context option outside of the class because `expressions are not allowed at the top level`.

- The models are all in the same and main bundle. Also made a call to:
```swift
        // Needed as your model probably is not in the main bundle
        contextOptions.modelBundle = NSBundle(forClass: DataModel.self)
```

Overall, I don't why the failable initializer isn't just letting me pass nothing to it.

**Comment by bguidolim** [comment]
+1

**Comment by vmartinelli** [comment]
Please check the last commit on `develop` branch. Perhaps the changes have brought solutions to the problems they are facing.
