### ISSUE TITLE
Enable/Disable iCloud?

### ISSUE THREAD

**Issue by bettimms** [Alecrim/AlecrimCoreData#75]
Hi,

Just updated to latest version and seems there's a change on <b>contextOptions.ubiquityEnabled</b> (can't set anymore).
How to enable/disable(control) iCloud on latest version of AlecrimCoreData.
I see also some other options are missing like <b>contextOptions.migratePersistentStoresAutomatically</b>.

Any workaround?!

Thanks & Regards,

**Comment by vmartinelli** [comment]
Hello.

In the current version you can configure iCloud integration with `configureUbiquityOptionsWithUbiquitousContainerIdentifier: ubiquitousContentURL: ubiquitousContentName:` available in `ContextOptions` struct.

(In this version, any observers to iCloud notifications has to be added by you. Since the `Context` is now a `NSManagedObjectContext` subclass you can observe the context directly.)

About the former `migratePersistentStoresAutomatically` property, it is now accessible using the `options` property of `ContextOptions` (that defaults to `[NSMigratePersistentStoresAutomaticallyOption : true, NSInferMappingModelAutomaticallyOption : true]`).

Please let me know if this solves your problem.

**Comment by bettimms** [comment]
Thanks for your answers!

The new implementation is giving more options and seems to be more flexible by offering to observe context directly (didn't try yet).
Regarding what i pointed out on first question, let's say we enable iCloud by ```configureUbiquityOptionsWithUbiquitousContainerIdentifier:ubiquitousContentURL:ubiquitousContentName: ```  but how would we disable it after enabling?!

Thanks

**Comment by vmartinelli** [comment]
Well... I think we don't have a way to disable iCloud once it was enabled for the context, but you may create another context with the same store as target without iCloud enabled. I don't know, however, if it will work this way or the involved implications.
